import { notFound } from 'next/navigation';
import type { JSX } from 'react';
import { fotoPath, getAllZpravy, getPublisherById, getZpravaBySlug, parseFotkyPopisek } from '../../../lib/content';
import { createDateFromDbDatetime, formatPublished } from '../../../lib/date-utils';

export async function generateStaticParams() {
  const rows = await getAllZpravy();
  return rows.map(z => ({ slug: `${z.rok}-${z.idr}` }));
}

export const metadata = { title: 'Zprávy – detail' };

type PageProps = { params: Promise<{ slug: string }> };

export default async function ZpravaDetail({ params }: PageProps): Promise<JSX.Element> {
  const { slug } = await params;
  let data: Awaited<ReturnType<typeof getZpravaBySlug>>;
  try {
    data = await getZpravaBySlug(slug);
  } catch {
    return notFound();
  }
  const z = data.item;
  const captions = parseFotkyPopisek(z.foto_popisek);
  const pub = await getPublisherById(z.vlozil);
  if (!pub) throw new Error(`Publisher ${z.vlozil} not found`);

  const prev = data.prev;
  const next = data.next;
  const publishedDate = createDateFromDbDatetime(z.datum_iso);

  return (
    <article className="prose">
      <p className="breadcrumbs">
        <a href="/zpravy">Zprávy</a>
        <span> / </span>
        <a href={`/zpravy#rok-${z.rok}`}>{z.rok}</a>
      </p>
      <h1>{z.nazev}</h1>
      <p className="byline"><em>{z.autor}</em></p>
      <div dangerouslySetInnerHTML={{ __html: z.text.replace(/<!--\s*Generated by XStandard[\s\S]*?-->/, '') }} />
      {Array.from({ length: z.foto_pocet }).map((_, x) => {
        const i1 = x + 1;
        const src = fotoPath(z.rok, z.foto_nazev, i1);
        const alt = captions[x] ?? '';
        return (
          <figure key={i1}>
            <img src={src} alt={alt} />
            {alt ? <figcaption>{alt}</figcaption> : null}
          </figure>
        );
      })}
      <hr />
      <section className="article-meta">
        <p>
          Publikoval
          {' '}
          <span>{pub.name}</span>
          {' '}
          <time dateTime={publishedDate.toISOString()}>{formatPublished(publishedDate)}</time>
        </p>
        <nav className="article-nav">
          <span>
            {prev && (
              <a href={`/zpravy/${prev.rok}-${prev.idr}`}>
                <span>&larr; </span>
                <span>{prev.nazev}</span>
              </a>
            )}
          </span>
          <span>
            {next && (
              <a href={`/zpravy/${next.rok}-${next.idr}`}>
                <span>{next.nazev}</span>
                <span> &rarr;</span>
              </a>
            )}
          </span>
        </nav>
      </section>
    </article>
  );
}
