import BrandLink from '@/components/brand-link';
import PageTitle from '@/components/page-title';
import Prose from '@/components/prose';

import { createDateFromDbDatetime, formatDate, formatPublished } from '@/lib/date-utils';
import { toAbsoluteUrl } from '@/lib/site';
import { getPublisherById } from '@/lib/users';
import { fotoPath, getAllZpravy, getZpravaBySlug, type Zprava } from '@/lib/zpravy';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import type { JSX } from 'react';

export async function generateStaticParams() {
  const rows = await getAllZpravy();
  return rows.map(z => ({ slug: `${z.rok}-${z.idr}` }));
}

type PageProps = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;

  const { item } = await getZpravaBySlug(slug);
  if (!item) throw new Error(`Zprava with slug ${slug} not found`);

  const { title, description, url, publishedTime } = createMetadata(item);

  return {
    title: `${title} | Zprávy ${item.rok}`,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'article',
      url,
      title,
      description,
      publishedTime,
    },
  } satisfies Metadata;
}

function createMetadata(item: Zprava) {
  const url = toAbsoluteUrl(`/zpravy/${item.rok}-${item.idr}`);
  const title = item.nazev;
  const published = createDateFromDbDatetime(item.datum_iso);
  const description = `Archiv webového článku farnosti Přibyslav ze dne ${formatDate(published)}.`;
  const publishedTime = published.toISOString();
  return { title, description, url, publishedTime };
}

function createJsonLd(zprava: Zprava) {
  const metadata = createMetadata(zprava);
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    'headline': metadata.title,
    'description': metadata.description,
    'author': zprava.autor,
    'url': metadata.url,
    'datePublished': metadata.publishedTime,
  } as const;
  return jsonLd;
}

export default async function ZpravaDetail({ params }: PageProps): Promise<JSX.Element> {
  const { slug } = await params;
  let data: Awaited<ReturnType<typeof getZpravaBySlug>>;
  try {
    data = await getZpravaBySlug(slug);
  } catch {
    return notFound();
  }
  const z = data.item;
  const captions = z.fotky ?? [];
  const pub = await getPublisherById(z.vlozil);
  if (!pub) throw new Error(`Publisher ${z.vlozil} not found`);

  const prev = data.prev;
  const next = data.next;
  const publishedDate = createDateFromDbDatetime(z.datum_iso);
  const html = z.text.replace(/<!--\s*Generated by XStandard[\s\S]*?-->/, '');

  return (
    <article>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(createJsonLd(z)) }}
      />
      <div className="mt-4 mb-4 text-xl font-semibold">
        <BrandLink href="/zpravy">Zprávy</BrandLink>
        <span> / </span>
        <BrandLink href={`/zpravy#rok-${z.rok}`}>{z.rok}</BrandLink>
      </div>
      <PageTitle className="mb-2">{z.nazev}</PageTitle>
      <div className="mb-8 text-amber-900 font-semibold"><em>{z.autor}</em></div>
      <Prose>
        <div dangerouslySetInnerHTML={{ __html: html }} />
        {Array.from({ length: z.foto_pocet }).map((_, x) => {
          const i1 = x + 1;
          const src = fotoPath(z.rok, z.foto_nazev, i1);
          const caption = captions[x];
          const alt = caption ?? `${z.nazev} – fotografie ${i1}`;
          return (
            <figure key={i1}>
              <img src={src} alt={alt} />
              {caption ? <figcaption dangerouslySetInnerHTML={{ __html: caption }} /> : null}
            </figure>
          );
        })}
      </Prose>
      <section className="bg-white py-3 px-4 rounded-lg border-amber-200 border mt-8">
        <p className="text-gray-950/50 text-center text-balance md:text-left">
          Publikoval
          {' '}
          <span className="text-amber-950">{pub.name}</span>
          {' dne '}
          <time
            className="text-amber-950"
            dateTime={publishedDate.toISOString()}
          >
            {formatPublished(publishedDate)}
          </time>
        </p>
        <nav className="flex justify-evenly md:justify-between flex-wrap md:flex-nowrap gap-4 mt-3">
          <span className="text-center">
            {prev && (
              <BrandLink href={`/zpravy/${prev.rok}-${prev.idr}`}>
                <span>&larr; </span>
                <span>{prev.nazev}</span>
              </BrandLink>
            )}
          </span>
          <span className="text-center">
            {next && (
              <BrandLink href={`/zpravy/${next.rok}-${next.idr}`}>
                <span>{next.nazev}</span>
                <span> &rarr;</span>
              </BrandLink>
            )}
          </span>
        </nav>
      </section>
    </article>
  );
}
